#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "\nRunning prettier on check mode...\n========================"
npm run p:check
echo "\nRunning eslint on check mode...\n========================"
npm run e:check